// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: aruna/api/storage/services/v2/endpoint_service.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EndpointService_CreateEndpoint_FullMethodName     = "/aruna.api.storage.services.v2.EndpointService/CreateEndpoint"
	EndpointService_FullSyncEndpoint_FullMethodName   = "/aruna.api.storage.services.v2.EndpointService/FullSyncEndpoint"
	EndpointService_SetEndpointStatus_FullMethodName  = "/aruna.api.storage.services.v2.EndpointService/SetEndpointStatus"
	EndpointService_GetEndpoint_FullMethodName        = "/aruna.api.storage.services.v2.EndpointService/GetEndpoint"
	EndpointService_GetEndpoints_FullMethodName       = "/aruna.api.storage.services.v2.EndpointService/GetEndpoints"
	EndpointService_DeleteEndpoint_FullMethodName     = "/aruna.api.storage.services.v2.EndpointService/DeleteEndpoint"
	EndpointService_GetDefaultEndpoint_FullMethodName = "/aruna.api.storage.services.v2.EndpointService/GetDefaultEndpoint"
)

// EndpointServiceClient is the client API for EndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointServiceClient interface {
	// CreateEndpoint
	//
	// Status: BETA
	//
	// Registers a new Endpoint (Aruna DataProxy) to the server
	// requires admin permissions
	CreateEndpoint(ctx context.Context, in *CreateEndpointRequest, opts ...grpc.CallOption) (*CreateEndpointResponse, error)
	// FullSyncEndpoint
	//
	// Status: BETA
	//
	// Requests a full sync of all endpoint related data
	FullSyncEndpoint(ctx context.Context, in *FullSyncEndpointRequest, opts ...grpc.CallOption) (EndpointService_FullSyncEndpointClient, error)
	// SetEndpointStatus
	//
	// Status: BETA
	//
	// This request sets the status of a specific Endpoint
	SetEndpointStatus(ctx context.Context, in *SetEndpointStatusRequest, opts ...grpc.CallOption) (*SetEndpointStatusResponse, error)
	// GetEndpoint
	//
	// Status: BETA
	//
	// Gets an specific endpoint by ID or Name
	GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error)
	// GetEndpoints
	//
	// Status: BETA
	//
	// Gets all available endpoints
	GetEndpoints(ctx context.Context, in *GetEndpointsRequest, opts ...grpc.CallOption) (*GetEndpointsResponse, error)
	// DeleteEndpoint
	//
	// Status: BETA
	//
	// Deletes a specific endpoint by id
	// This needs admin permissions
	DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error)
	// GetDefaultEndpoint
	//
	// Status: BETA
	//
	// This request returns the default endpoint for the current aruna_server
	// It may produce different results depending on the used server
	GetDefaultEndpoint(ctx context.Context, in *GetDefaultEndpointRequest, opts ...grpc.CallOption) (*GetDefaultEndpointResponse, error)
}

type endpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointServiceClient(cc grpc.ClientConnInterface) EndpointServiceClient {
	return &endpointServiceClient{cc}
}

func (c *endpointServiceClient) CreateEndpoint(ctx context.Context, in *CreateEndpointRequest, opts ...grpc.CallOption) (*CreateEndpointResponse, error) {
	out := new(CreateEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointService_CreateEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) FullSyncEndpoint(ctx context.Context, in *FullSyncEndpointRequest, opts ...grpc.CallOption) (EndpointService_FullSyncEndpointClient, error) {
	stream, err := c.cc.NewStream(ctx, &EndpointService_ServiceDesc.Streams[0], EndpointService_FullSyncEndpoint_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointServiceFullSyncEndpointClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EndpointService_FullSyncEndpointClient interface {
	Recv() (*FullSyncEndpointResponse, error)
	grpc.ClientStream
}

type endpointServiceFullSyncEndpointClient struct {
	grpc.ClientStream
}

func (x *endpointServiceFullSyncEndpointClient) Recv() (*FullSyncEndpointResponse, error) {
	m := new(FullSyncEndpointResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *endpointServiceClient) SetEndpointStatus(ctx context.Context, in *SetEndpointStatusRequest, opts ...grpc.CallOption) (*SetEndpointStatusResponse, error) {
	out := new(SetEndpointStatusResponse)
	err := c.cc.Invoke(ctx, EndpointService_SetEndpointStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) GetEndpoint(ctx context.Context, in *GetEndpointRequest, opts ...grpc.CallOption) (*GetEndpointResponse, error) {
	out := new(GetEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointService_GetEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) GetEndpoints(ctx context.Context, in *GetEndpointsRequest, opts ...grpc.CallOption) (*GetEndpointsResponse, error) {
	out := new(GetEndpointsResponse)
	err := c.cc.Invoke(ctx, EndpointService_GetEndpoints_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error) {
	out := new(DeleteEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointService_DeleteEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointServiceClient) GetDefaultEndpoint(ctx context.Context, in *GetDefaultEndpointRequest, opts ...grpc.CallOption) (*GetDefaultEndpointResponse, error) {
	out := new(GetDefaultEndpointResponse)
	err := c.cc.Invoke(ctx, EndpointService_GetDefaultEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointServiceServer is the server API for EndpointService service.
// All implementations should embed UnimplementedEndpointServiceServer
// for forward compatibility
type EndpointServiceServer interface {
	// CreateEndpoint
	//
	// Status: BETA
	//
	// Registers a new Endpoint (Aruna DataProxy) to the server
	// requires admin permissions
	CreateEndpoint(context.Context, *CreateEndpointRequest) (*CreateEndpointResponse, error)
	// FullSyncEndpoint
	//
	// Status: BETA
	//
	// Requests a full sync of all endpoint related data
	FullSyncEndpoint(*FullSyncEndpointRequest, EndpointService_FullSyncEndpointServer) error
	// SetEndpointStatus
	//
	// Status: BETA
	//
	// This request sets the status of a specific Endpoint
	SetEndpointStatus(context.Context, *SetEndpointStatusRequest) (*SetEndpointStatusResponse, error)
	// GetEndpoint
	//
	// Status: BETA
	//
	// Gets an specific endpoint by ID or Name
	GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error)
	// GetEndpoints
	//
	// Status: BETA
	//
	// Gets all available endpoints
	GetEndpoints(context.Context, *GetEndpointsRequest) (*GetEndpointsResponse, error)
	// DeleteEndpoint
	//
	// Status: BETA
	//
	// Deletes a specific endpoint by id
	// This needs admin permissions
	DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error)
	// GetDefaultEndpoint
	//
	// Status: BETA
	//
	// This request returns the default endpoint for the current aruna_server
	// It may produce different results depending on the used server
	GetDefaultEndpoint(context.Context, *GetDefaultEndpointRequest) (*GetDefaultEndpointResponse, error)
}

// UnimplementedEndpointServiceServer should be embedded to have forward compatible implementations.
type UnimplementedEndpointServiceServer struct {
}

func (UnimplementedEndpointServiceServer) CreateEndpoint(context.Context, *CreateEndpointRequest) (*CreateEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEndpoint not implemented")
}
func (UnimplementedEndpointServiceServer) FullSyncEndpoint(*FullSyncEndpointRequest, EndpointService_FullSyncEndpointServer) error {
	return status.Errorf(codes.Unimplemented, "method FullSyncEndpoint not implemented")
}
func (UnimplementedEndpointServiceServer) SetEndpointStatus(context.Context, *SetEndpointStatusRequest) (*SetEndpointStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEndpointStatus not implemented")
}
func (UnimplementedEndpointServiceServer) GetEndpoint(context.Context, *GetEndpointRequest) (*GetEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndpoint not implemented")
}
func (UnimplementedEndpointServiceServer) GetEndpoints(context.Context, *GetEndpointsRequest) (*GetEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEndpoints not implemented")
}
func (UnimplementedEndpointServiceServer) DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEndpoint not implemented")
}
func (UnimplementedEndpointServiceServer) GetDefaultEndpoint(context.Context, *GetDefaultEndpointRequest) (*GetDefaultEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultEndpoint not implemented")
}

// UnsafeEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServiceServer will
// result in compilation errors.
type UnsafeEndpointServiceServer interface {
	mustEmbedUnimplementedEndpointServiceServer()
}

func RegisterEndpointServiceServer(s grpc.ServiceRegistrar, srv EndpointServiceServer) {
	s.RegisterService(&EndpointService_ServiceDesc, srv)
}

func _EndpointService_CreateEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).CreateEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_CreateEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).CreateEndpoint(ctx, req.(*CreateEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_FullSyncEndpoint_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FullSyncEndpointRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointServiceServer).FullSyncEndpoint(m, &endpointServiceFullSyncEndpointServer{stream})
}

type EndpointService_FullSyncEndpointServer interface {
	Send(*FullSyncEndpointResponse) error
	grpc.ServerStream
}

type endpointServiceFullSyncEndpointServer struct {
	grpc.ServerStream
}

func (x *endpointServiceFullSyncEndpointServer) Send(m *FullSyncEndpointResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EndpointService_SetEndpointStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEndpointStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).SetEndpointStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_SetEndpointStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).SetEndpointStatus(ctx, req.(*SetEndpointStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_GetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).GetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_GetEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).GetEndpoint(ctx, req.(*GetEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_GetEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).GetEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_GetEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).GetEndpoints(ctx, req.(*GetEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_DeleteEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).DeleteEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_DeleteEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).DeleteEndpoint(ctx, req.(*DeleteEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointService_GetDefaultEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServiceServer).GetDefaultEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndpointService_GetDefaultEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServiceServer).GetDefaultEndpoint(ctx, req.(*GetDefaultEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndpointService_ServiceDesc is the grpc.ServiceDesc for EndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aruna.api.storage.services.v2.EndpointService",
	HandlerType: (*EndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEndpoint",
			Handler:    _EndpointService_CreateEndpoint_Handler,
		},
		{
			MethodName: "SetEndpointStatus",
			Handler:    _EndpointService_SetEndpointStatus_Handler,
		},
		{
			MethodName: "GetEndpoint",
			Handler:    _EndpointService_GetEndpoint_Handler,
		},
		{
			MethodName: "GetEndpoints",
			Handler:    _EndpointService_GetEndpoints_Handler,
		},
		{
			MethodName: "DeleteEndpoint",
			Handler:    _EndpointService_DeleteEndpoint_Handler,
		},
		{
			MethodName: "GetDefaultEndpoint",
			Handler:    _EndpointService_GetDefaultEndpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FullSyncEndpoint",
			Handler:       _EndpointService_FullSyncEndpoint_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aruna/api/storage/services/v2/endpoint_service.proto",
}
