// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: aruna/api/hooks/services/v1/hooks_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HooksServiceClient is the client API for HooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HooksServiceClient interface {
	CreateHook(ctx context.Context, in *CreateHookRequest, opts ...grpc.CallOption) (*CreateHookResponse, error)
	ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error)
	DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error)
	HookCallback(ctx context.Context, in *HookCallbackRequest, opts ...grpc.CallOption) (*HookCallbackResponse, error)
}

type hooksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHooksServiceClient(cc grpc.ClientConnInterface) HooksServiceClient {
	return &hooksServiceClient{cc}
}

func (c *hooksServiceClient) CreateHook(ctx context.Context, in *CreateHookRequest, opts ...grpc.CallOption) (*CreateHookResponse, error) {
	out := new(CreateHookResponse)
	err := c.cc.Invoke(ctx, "/aruna.api.hooks.services.v1.HooksService/CreateHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) ListHooks(ctx context.Context, in *ListHooksRequest, opts ...grpc.CallOption) (*ListHooksResponse, error) {
	out := new(ListHooksResponse)
	err := c.cc.Invoke(ctx, "/aruna.api.hooks.services.v1.HooksService/ListHooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) DeleteHook(ctx context.Context, in *DeleteHookRequest, opts ...grpc.CallOption) (*DeleteHookResponse, error) {
	out := new(DeleteHookResponse)
	err := c.cc.Invoke(ctx, "/aruna.api.hooks.services.v1.HooksService/DeleteHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) HookCallback(ctx context.Context, in *HookCallbackRequest, opts ...grpc.CallOption) (*HookCallbackResponse, error) {
	out := new(HookCallbackResponse)
	err := c.cc.Invoke(ctx, "/aruna.api.hooks.services.v1.HooksService/HookCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HooksServiceServer is the server API for HooksService service.
// All implementations should embed UnimplementedHooksServiceServer
// for forward compatibility
type HooksServiceServer interface {
	CreateHook(context.Context, *CreateHookRequest) (*CreateHookResponse, error)
	ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error)
	DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error)
	HookCallback(context.Context, *HookCallbackRequest) (*HookCallbackResponse, error)
}

// UnimplementedHooksServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHooksServiceServer struct {
}

func (UnimplementedHooksServiceServer) CreateHook(context.Context, *CreateHookRequest) (*CreateHookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHook not implemented")
}
func (UnimplementedHooksServiceServer) ListHooks(context.Context, *ListHooksRequest) (*ListHooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHooks not implemented")
}
func (UnimplementedHooksServiceServer) DeleteHook(context.Context, *DeleteHookRequest) (*DeleteHookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHook not implemented")
}
func (UnimplementedHooksServiceServer) HookCallback(context.Context, *HookCallbackRequest) (*HookCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HookCallback not implemented")
}

// UnsafeHooksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HooksServiceServer will
// result in compilation errors.
type UnsafeHooksServiceServer interface {
	mustEmbedUnimplementedHooksServiceServer()
}

func RegisterHooksServiceServer(s grpc.ServiceRegistrar, srv HooksServiceServer) {
	s.RegisterService(&HooksService_ServiceDesc, srv)
}

func _HooksService_CreateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).CreateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aruna.api.hooks.services.v1.HooksService/CreateHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).CreateHook(ctx, req.(*CreateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_ListHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).ListHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aruna.api.hooks.services.v1.HooksService/ListHooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).ListHooks(ctx, req.(*ListHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_DeleteHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).DeleteHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aruna.api.hooks.services.v1.HooksService/DeleteHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).DeleteHook(ctx, req.(*DeleteHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_HookCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).HookCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aruna.api.hooks.services.v1.HooksService/HookCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).HookCallback(ctx, req.(*HookCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HooksService_ServiceDesc is the grpc.ServiceDesc for HooksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HooksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aruna.api.hooks.services.v1.HooksService",
	HandlerType: (*HooksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHook",
			Handler:    _HooksService_CreateHook_Handler,
		},
		{
			MethodName: "ListHooks",
			Handler:    _HooksService_ListHooks_Handler,
		},
		{
			MethodName: "DeleteHook",
			Handler:    _HooksService_DeleteHook_Handler,
		},
		{
			MethodName: "HookCallback",
			Handler:    _HooksService_HookCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aruna/api/hooks/services/v1/hooks_service.proto",
}
